### ISSUE TITLE
ECData is now ECWeather

### ISSUE THREAD

**Issue by m0yellow** [probnot/wpg-weatherchan#2]
Hello,
while trying out your great project, I run into an issue, with ECData not available. 
The fix described in here worked for me.

https://github.com/michaeldavie/env_canada/issues/33

Another solution would be, to provide sample information for anybody wanting to try your great idea, without working with the dependency heavy env_canada (especially when not from Canada, as I am).

You can close this issue right away, if you want to fix ECData in another issue, I have fixed it locally, exactly as described in the link provided. (But I don't mind if you want to leave it open, having me as the "requestor").
Happy New Year, 
Matthias

**Comment by michaeldavie** [comment]
Yup, I changed things around a bit in v0.3.0 of `env_canada`. Another option would be to install v0.2.5 (`pip install env_canda==0.2.5`), which uses the old structure and has been updated to work with Python 3.9.
